### ISSUE TITLE
t_lib: getStatData curl error

### ISSUE THREAD

**Issue by unlstorm** [ThermoMan/Thermostat-Tracking#51] opened 2014-02-08 15:17 UTC
I'm seeing some occasional sequences of events that are resulting in errors and dead data in my charts.  Below are logs.

2014-02-08 7:07:01 - INFO --> status: start
2014-02-08 7:07:08 - INFO --> status: execution time was 6.7134218215942 seconds.
2014-02-08 7:08:01 - INFO --> status: start
2014-02-08 7:08:15 - WARN --> t_lib: getStatData curl error (Operation timed out after 10006 millisec
2014-02-08 7:08:25 - WARN --> t_lib: Made 2 attempts and last curl status was 0
2014-02-08 7:08:25 - INFO --> status: execution time was 24.12618803978 seconds.
2014-02-08 7:09:01 - INFO --> status: start
2014-02-08 7:09:15 - WARN --> t_lib: getStatData curl error (Operation timed out after 10006 millisec
2014-02-08 7:09:26 - WARN --> t_lib: getStatData curl error (Operation timed out after 10006 millisec
2014-02-08 7:09:37 - WARN --> t_lib: getStatData curl error (Operation timed out after 10006 millisec
2014-02-08 7:09:38 - WARN --> t_lib: Made 3 attempts and last curl status was 28
2014-02-08 7:09:38 - ERROR --> t_lib: getStatData communication error.
2014-02-08 7:09:38 - ERROR --> t_lib: containsTransient: argument obj was NOT an object!
2014-02-08 7:09:38 - ERROR --> status: Thermostat failed to respond with present status
2014-02-08 7:09:38 - INFO --> status: execution time was 36.600104093552 seconds.
2014-02-08 7:10:01 - INFO --> status: start

**Comment by unlstorm** [comment] 2018-04-08 22:34
Hi ThermoMan. I'm still seeing this error sometimes in my logs. Did you have a fix for this that worked? I am still on some older code.

**Comment by ThermoMan** [comment] 2018-04-09 07:10
No fix, though I think I did figure out a couple of contributing factors.

The brains in the thermostat are not the fastest things in the world and when I was using two services to monitor ( mine and the one at https://my.radiothermostat.com/filtrete/thermostat.html [ OR https://my.radiothermostat.com/rtcoa/thermostat.html depending on your version ] ) the little thing gets overwhelmed when too many queries come in at once and it resets the connection and for a couple of minutes won't talk to anyone (not even the Android app)

The other one I think is related to how fast your server is.  Mine is a low rent shared hosting setup and as the MySQL DB is filling up it's slowing down and that makes some of the requests (triggered by cron) stack up and all fire on top of each other (adding to problem #1 above)

**Comment by unlstorm** [comment] 2018-04-11 05:04
Interesting comments. I never even thought about the filtrete service monitor. I see that it's monitoring my thermostat clearly for the past year (wonder if they only keep 1 year of DB data?). I have some interesting log files but I've noticed a bit of issues lately where my NAS (which hosts my webserver and the database) is getting occasionally backed up with never ending cron tasks for the status script. I used to have this script doing once a minute queries and have recently moved it to once every 5 minutes. But I'm still getting periodic clogging of these cron tasks which never exit the process and then it eventually creates so many jobs that I run out of swap memory on my NAS until I either SSH into it and "killall synoschedtask" processes or I reboot the NAS server. I really need to get to the bottom of this because my NAS is the HUB of my home for nearly everything data and video stream sharing. I've attached some examples of my crond task issue and some of my logs where the hiccups occur. I'm curious if I adjust the timeouts to something much better (like a minute) if that would help?

![2018-03-30 22_40_43-nas matrix - putty](https://user-images.githubusercontent.com/2549596/38597002-8a7fba9a-3d1a-11e8-8699-d9270fc2da2d.png)

![2018-04-11 00_02_00-nas matrix - putty](https://user-images.githubusercontent.com/2549596/38597176-9f49b876-3d1b-11e8-955e-56e231313a4d.png)

**Comment by unlstorm** [comment] 2018-04-11 05:32
Look at these logs from my server around the 8th between roughly 6:20pm and 9pm. The status updates earlier are taking ~12 to 19 seconds and later they take ~7 to 11 seconds:

![2018-04-11 00_20_19-nas matrix - putty](https://user-images.githubusercontent.com/2549596/38597669-9c61bf98-3d1e-11e8-8eee-00a5a09c505a.png)

Then I get < 10 second updates for a couple more hours and after the temps and status updates happen simultaneous at 11:30pm the status updates jump to  > 10 seconds (and the cron job appears to no longer stay on 5 min intervals near the end):

![2018-04-11 00_25_20-nas matrix - putty](https://user-images.githubusercontent.com/2549596/38597786-4408f7b6-3d1f-11e8-93c9-df3f21b85ef6.png)

Then things really start falling apart in these next two captures:
![2018-04-11 00_30_58-nas matrix - putty](https://user-images.githubusercontent.com/2549596/38597913-d29615cc-3d1f-11e8-9a0b-991313397857.png)
![2018-04-11 00_32_02-nas matrix - putty](https://user-images.githubusercontent.com/2549596/38597917-d64e26b4-3d1f-11e8-91ce-18458fb8496e.png)

**Comment by unlstorm** [comment] 2018-04-11 05:46
I wonder if I can change priority or something of some of my cron tasks? Look at the timing fall apart in my 4/8/18 cron logs when I grep start times:

![2018-04-11 00_44_25-](https://user-images.githubusercontent.com/2549596/38598400-c92f788c-3d21-11e8-90a9-8d59281de0bd.png)

![2018-04-11 00_45_18-nas matrix - putty](https://user-images.githubusercontent.com/2549596/38598404-cbd97ad8-3d21-11e8-907f-fddd9cfbb0b8.png)

**Comment by unlstorm** [comment] 2018-04-11 06:24
I found that the task schedule on my NAS (called synoschedtask) has some run options called check_time and check_status that default to 1. I just changed these params to "check_time=0 check_status=0" and will let this go for a while to see if it helps the strange cron timing issues I've been seeing that may be leading into the issues I've been having:
![2018-04-11 01_22_04-nas matrix - putty](https://user-images.githubusercontent.com/2549596/38599679-20f06d24-3d27-11e8-9679-5cb4be92b31b.png)

**Comment by ThermoMan** [comment] 2018-04-11 07:39
One idea on the cron tasks.  
1. When you start a task touch a file with name list "taskname.PID" and when you end the task rm the file.  
2. Then have another cron task like once per hour that does a find for taskname.* that is older than 5 minutes and parse the PIDs from the filename and do a kill -9 on those processes and delete the files.  
3. And make a note in log file that PID had to be killed.

This will do a sort of self-clean so you clog up your NAS less often.

**Comment by Lerrissirrel** [comment] 2018-04-12 00:38
I don't have an answer for you, but I also get this problem periodically and I manually kill all the stuck processes (I do an equivalent of ThermoMan's #2 by hand each time).

For reference I've had both an old slow linux box and a new speedy one, and had the problem on both.

I also run munin node on the same linux box where I run this.  Munin might give another hint.  

It appears that the database connections aren't closing for those "stuck" instances of the script.  I can see the connections shoot from 0 to 100+ in a couple of hours.  I don't know if that's because the php script doesn't end (at which point I think a PDO connection would get closed automatically), or that the open db connection is what's preventing the script from ending.  I dug a little bit, but didn't see anything obvious, but I never spent any time in the script code.  Maybe this piece of information will trigger an idea for one of you!

I may sprinkle some explicit "closes" (setting the handle to 'null') around the script and see if that helps any.  Unfortunately this issue doesn't hit me very often!

**Comment by ThermoMan** [comment] 2018-04-12 01:42
It is bad practice not to close the DB connection.  I'm a bad toad.
It may be that when the PHP session ends that the database isn't cleaning up the connections and so some subsequent request for DB connection simply never returns.
Setting it to null seems to be the way to go ( per http://php.net/manual/en/pdo.connections.php )

In my setup I'll add a destructor to the Database object and put a null (and some logging) in there and see what happens.

**Comment by Lerrissirrel** [comment] 2018-04-13 00:18
Just to be clear, I think it is the php processes that never exit that are leaving the db connections open.    That's just a guess, but the two problems come together.  I'm not sure which is the cause and which is the effect.

Ironically, about 2 hours after I posted yesterday saying "it doesn't happen often" it happened again.  I didn't realize that there are methods to analyze what a process is doing while it's running until *after* I killed them all.  But next time it happens, I'll do some archeology on those stuck php scripts and see what I can find.

**Comment by ThermoMan** [comment] 2018-06-22 04:09
I've changed the depth of the retries and shorted some of the times.  There were a couple of cases where a timeout type error could stat up and push a request into a 90+ second ordeal - impacting the next minutes attempt to call in.

I'm also moving my code in house and so that will fix a ton of latency issues.  I'll close this issue and if after the new code push it's still an issue we can open a new one.

**Closed by ThermoMan** 2018-06-22 04:09 UTC
Labels: enhancement
